# Server
MAX_CONNECTIONS = 16
HOST = "192.168.6.39"
PORT = 2333
BUFFER_SIZE = 65536

# Parser
PARSE_CURRENT = True
PARSE_BOARD = True
PARSE_HISTORY = True
WHITE_CURRENT = "W"
BLACK_CURRENT = "B"
EMPTY_CHAR = "+"
WHITE_CHAR = "W"
BLACK_CHAR = "B"
