# Server
MAX_CONNECTIONS = 16
HOST = "127.0.0.1"
PORT = 2779
BUFFER_SIZE = 65536

# Parser
PARSE_CURRENT = True
PARSE_BOARD = True
PARSE_HISTORY = True
WHITE_CURRENT = "W"
BLACK_CURRENT = "B"
EMPTY_CHAR = "+"
WHITE_CHAR = "W"
BLACK_CHAR = "B"
